# Configuración del servidor
server.port=8080
spring.application.name=PaginaWebDivisas

# Configuración de la base de datos MySQL para producción
spring.datasource.url=jdbc:mysql://localhost:3306/divisas
spring.datasource.username=root
spring.datasource.password=Llens@jofre2
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de cookies y sesiones
server.servlet.session.cookie.same-site=None
server.servlet.session.cookie.secure=true

# Configuración de JPA y Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

