server.port=8080
spring.application.name=PaginaWebDivisas
spring.datasource.url=jdbc:mysql://localhost:3306/divisas
spring.datasource.username=root
spring.datasource.password=Llens@jofre2
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
server.servlet.session.cookie.same-site=None
server.servlet.session.cookie.secure=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect